batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 74
model_path: Models/Sentence_recognition/202306291003
train_epochs: 100
train_workers: 20
vocab: E/R9Cd?3F#vMhz*rISVOs0n1o7f(mwLe-QPt,:pDuH4G"g!WZ5jNy8kxYJqX'lcU)A;2.bTKB6
  ai
width: 1408
